### PR TITLE
Fix crash on Xiao Mi 7A when pick gif

### PR DESCRIPTION
**Pull request by tungtd95**

### CODE REVIEW

**Comment by Sh1d0w** [comment]
Hi, and thanks for the PR. How are you able to pick GIF images, when they should be filtered and not showing in the picker (see [this](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L545) line)? It should not be possible to pick GIF images at all.

**Comment by tungtd95** [comment]
> Hi, and thanks for the PR. How are you able to pick GIF images, when they should be filtered and not showing in the picker (see [this](https://github.com/Sh1d0w/multi_image_picker/blob/master/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L545) line)? It should not be possible to pick GIF images at all.

I haven't check for FishBun yet, but somehow the gif format is not excluded on Xiao Mi 7A.

**Comment by Sh1d0w** [comment]
You should report that to FishBun then if there is a bug. I don't think this will fix the problem at least not for the user. If he picked 3 images and two of them were GIFs, with your fix after he returns to the app he will see only one image as you skip the other two. Also From my tests if I enable GIF images and pick them they don't crash the app, they are just converted to JPEGs when I get the byte data. So the problem with the crash is something else. Do you have the full error that you get?

**Comment by tungtd95** [comment]
@Sh1d0w The exception was thrown on `map.put("identifier", uri.toString());` when uri is null. It happen when I pick an GIF image. Maybe GIF is not the root cause.

**Comment by Sh1d0w** [comment]
Yeah, unfortunately I don't have Xiomi device to test, so if you could dig up the problem and provide a fix that would be much appreciated :)

**Comment by tungtd95** [comment]
Thank you for response. I will close this PR for further investigation.

**Pull request closed without merging**
