### PR TITLE
Migrate to null safety

### LINKED ISSUE #630: Nullsafety support
Please migrate to null safety.

### LINKED ISSUE #633: Null safety
The new Dart version with null-safety was just released
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

### PR DESCRIPTION
**Pull request by SametSahin10**
I've used `dart migrate` to migrate package to null safety. I've also tried to remove any unnecessary assertions that was there to prevent a value from being null.

Fixes #633, fixes  #634, fixes #630.

### CODE REVIEW

**Comment by Sh1d0w** [comment]
Hi and thanks for the PR.

When I run this on the iOS simulator the app instantly crashes after I invoke the image picker. Can you please run it with Xcode and the what errors it is throwing? Thanks

**Comment by SametSahin10** [comment]
I've tried to run the app on iOS Simulator but I've got an error related Podfile. There's a [Stackoverflow question](https://stackoverflow.com/q/65516334/6753606) about it. [This](https://stackoverflow.com/a/65528871/6753606) answer helped me solve it. After that, I've managed to run the app and reproduce the crash. There was no log or a message about the crash so I've run the app with `flutter run --verbose`. Below is the related output:

```
[   +8 ms] Lost connection to device.
[  +67 ms] DevFS: Deleting filesystem on the device
(file:///Users/sametsahin/Library/Developer/CoreSimulator/Devices/707C1144-FAFF-40BF-B76B-CA2704280BAB/data/Containers/Data/Application/D41530B7-C50D-43BA-87A
9-27B262E83F34/tmp/examplebTNC5u/example/)
[ +261 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 54,764ms.
[ +257 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 0
```

Not descriptive enough for sure. I've searched for a solution but I couldn't find anything. Do you have an idea? @Sh1d0w

**Comment by fzyzcjy** [comment]
Do you have enough permissions on your simulator - For example, does the "request permission" dialog popup when you first run it? Maybe that is a possible reason

**Comment by Sh1d0w** [comment]
Actually I had a time to look into this. To get the error you need to run it with Xcode directly. It was related to missing NSPhotoLibraryUsageDescription in Info.plist:

Screenshot 2021-03-06 at 6 00 58

After I've added it the app was working fine. Thanks for your work and PRs @SametSahin10 and @fzyzcjy 

I am going to merge this.

**Pull request merged**
