### PR TITLE
Fix FormatException (invalid double) in castAsDouble when loading metadata

### LINKED ISSUE #274: Unhandled FormatException while getting MetaData
**Bug Report**

`multi_image_picker` version: ^4.5.5

Is it happening on Android: Yes

Is it happening on iOS: Not tested

```
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G103, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

**Describe the bug**

This error is happening for some pictures from my gallery but other pictures are fine.

I am calling it like this

```
 Metadata meta = await asset.metadata;
```

E/flutter (23913): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid double
E/flutter (23913): 6432/1000
E/flutter (23913): #0      double.parse (dart:core-patch/double_patch.dart:110:28)
E/flutter (23913): #1      _castAsDouble (package:multi_image_picker/src/metadata.dart:961:43)
E/flutter (23913): #2      new GpsMetadata.fromMap (package:multi_image_picker/src/metadata.dart:843:18)
E/flutter (23913): #3      new Metadata.fromMap (package:multi_image_picker/src/metadata.dart:13:27)
E/flutter (23913): #4      MultiImagePicker.requestMetadata (package:multi_image_picker/src/picker.dart:170:21)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #5      Asset.metadata (package:multi_image_picker/src/asset.dart:137:29)
E/flutter (23913): #6      NativeImagePickerRegistry.multiPickImages.<anonymous closure> (package:restra_mvp/services/native_image_picker.dart:49:35)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #7      Future.forEach.<anonymous closure> (dart:async/future.dart:492:26)
E/flutter (23913): #8      Future.doWhile.<anonymous closure> (dart:async/future.dart:534:26)
E/flutter (23913): #9      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23913): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23913): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23913): #12     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (23913): #13     Future.doWhile (dart:async/future.dart:549:18)
E/flutter (23913): #14     Future.forEach (dart:async/future.dart:490:12)
E/flutter (23913): #15     NativeImagePickerRegistry.multiPickImages (package:restra_mvp/services/native_image_picker.dart:42:18)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #16     PictureBlogBloc.getImage (package:restra_core/src/blocs/input/picture_blog_bloc.dart:33:10)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #17     InputSystem.build.<anonymous closure> (package:restra_mvp/ui/input/input.dart:271:73)
E/flutter (23913): <asynchronous suspension>
E/flutter (23913): #18     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:655:14)
E/flutter (23913): #19     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:730:32)
E/flutter (23913): #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23913): #21     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (23913): #22     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (23913): #23     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (23913): #24     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (23913): #25     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (23913): #26     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (23913): #27     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23913): #28     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23913): #29     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23913): #30     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23913): #31     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (23913): #32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23913): #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23913): #34     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (23913): #35     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

### PR DESCRIPTION
**Pull request by eug48**
This adds support for rational (numerator/denominator) strings which are returned by `androidx.exifinterface.media.ExifInterface` for tags like TAG_GPS_DOP:

https://github.com/Sh1d0w/multi_image_picker/blob/3d1a008a1f154b76647777bd50ea78adb38349bc/android/src/main/java/com/vitanov/multiimagepicker/MultiImagePickerPlugin.java#L491
--> https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-exifinterface-release/exifinterface/exifinterface/src/main/java/androidx/exifinterface/media/ExifInterface.java#4106
--> https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-exifinterface-release/exifinterface/exifinterface/src/main/java/androidx/exifinterface/media/ExifInterface.java#3434

For some reason I'm only getting reports of errors on Pixel phones - maybe other phones don't add these GPS tags.

This may well fix #274 and #486.

### CODE REVIEW

**Comment by Sh1d0w** [comment]
Hi @eug48 and thanks for your PR. Looking into this I don't think the is the correct fix.

On android side of things I can see the `ExifInterface.TAG_GPS_DOP` is extracted as string (see [here](ExifInterface.TAG_GPS_DOP,)), but on Flutter side I've for some reason defined it as double (see [here](https://github.com/Sh1d0w/multi_image_picker/blob/master/lib/src/metadata.dart#L714)).

Looking in ExifInterface docs ([here](https://developer.android.com/reference/android/media/ExifInterface#TAG_GPS_DOP)) I see it is defined as string so the correct fix should be to just change the variable definition in `metadata.dart` from double to string, which will resolve the issue. 

Thanks for your contribution, I will close this now and will amend the variable type in `metadata.dart` 👍

**Comment by eug48** [comment]
Hi @Sh1d0w - thanks for reviewing the PR and this great package. Treating it as a string will work, but it is actually a rational (i.e. fraction) number type. That link from the ExifInterface docs is referring to the type of the tag itself as a string, whereas the value type is rational. So converting to a double might be more helpful to some rare users, but I don't actually mind.

However another point is that this issue likely applies to other rational-type tags as well.

**Comment by Sh1d0w** [comment]
Ah you are right, the type is rational.

Then the correct fix should be to parse and return all rational types from ExifInterface on java side. If you want to pick up this task that would be the correct fix I think 👍

**Comment by eug48** [comment]
Okay sure, I think the best way to fix it on the java side is to move the rational tags from `tags_24_str` to `tags24_double`. They will then be retrieved with `exifInterface.getAttributeDouble` which is slightly faster than `exifInterface.getAttribute` because the Rational values are stored internally as numbers - and we don't have to do any string parsing.

I can only see `TAG_GPS_DOP` and `TAG_GPS_IMG_DIRECTION` that can be moved - can test and amend this PR. How does this sound?

I've also noticed another issue - `exifInterface.getAttributeDouble` crashes with `NumberFormatException("There are more than one component")` for multi-valued attributes, and some attributes like `YCbCrCoefficients` are definitely multi-valued but are in `tags24_double`. Treating them as strings is probably the easiest workaround.. I would think most applications don't need them fully parsed.

**Comment by Sh1d0w** [comment]
That's sounds reasonable. Thanks for looking into this. I will reopen the PR.

**Comment by eug48** [comment]
Hi @Sh1d0w, I've updated the patch and tested it on both Android and iOS

**Review by Sh1d0w — APPROVED** [review]

**Pull request merged**
