### PR TITLE
Adding support for Android API Level 16 and up

### PR DESCRIPTION
**Pull request by jpainam**
I added some functions to take into account the different API Levels.
I completely rewrite the `getOrientation` function since you were using MediaStore.Images.ImageColumns.ORIENTATION which was introduced in API Level 29. I used `ExifInterface`.
Some of the code to support API Level < 19 was taken from `https://gist.github.com/tatocaster/32aad15f6e0c50311626`

### CODE REVIEW

**Comment by Sh1d0w** [comment]
Thanks for the PR, looks good!

**Comment by Martibis** [comment]
This completely breaks on Android 10 with images being rotated incorrectly.

**Comment by jpainam** [comment]
Hi, please, when you said, it does seem to be happening since the latest version, you mean, the bug also occurs on the 4.6.1 (version before the PR) or only on 4.6.2 (after the PR)?
Sorry, i didn't get you well.

**Comment by Sh1d0w** [comment]
@jpainam I guess we need to rollback [this](https://github.com/Sh1d0w/multi_image_picker/pull/399/files#diff-a1e9afd876d647cc741fa9593d690b03L704) block change. Not all images contain the orientation meta tag, that's why I was using the MediaStore. I am going to revert this PR and release a new version, if you wish you can submit new PR that has proper orientation check.

@Martibis Sorry for the inconvenience, I should have released this as RC not minor version bump.

**Comment by jpainam** [comment]
@Sh1d0w I think keeping support for API Level 16 is the way forward and a good idea. I'll submit a PR that handles the case where the orientation tag is missing. A simple thing to do now is fallback to your implementation if the android sdk version is  > 19.

**Comment by Sh1d0w** [comment]
@jpainam I completely agree, thanks for the effort and time you are putting into this, it is much appreciated 👍 

Btw now that I am looking into this it seems for ExifInterface check you need to tweak the values returned from this function, as currently it is returning different things. The current code expects degrees to be returned, however the library returns another const. You should probably change to something like this:

```
int orientation = exifInterface.getAttributeInt(ExifInterface.TAG_ORIENTATION, 1);
            int rotationDegrees = 0;
            switch (orientation) {
                case ExifInterface.ORIENTATION_ROTATE_90:
                    rotationDegrees = 90;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_180:
                    rotationDegrees = 180;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_270:
                    rotationDegrees = 270;
                    break;
            }

           return rotationDegrees;
```

See [here](https://developer.android.com/reference/android/media/ExifInterface#ORIENTATION_ROTATE_90) and [here](https://github.com/google/cameraview/issues/22) for reference.

I guess this may be causing the issue reported by @Martibis and you code could be possibly working fine after this change, but needs to be tested.

**Comment by Martibis** [comment]
@Sh1d0w Glad I could catch it, and thanks for the swift reply.

@jpainam It happens only on 4.6.2.

**Comment by jpainam** [comment]
@Sh1d0w you are right about the const values. the returned value needs to be changed. I updated my fork repository to solve this #407 and #405. I'll submit a PR. @Martibis can also double-check if the problem is solved

**Pull request merged**
