### PR TITLE
Tmp fix on android ExifInterface latitude, longitude reading error

### PR DESCRIPTION
**Pull request by Quanalogy**
Workaround for https://issuetracker.google.com/issues/133039056 to be able to read gps latitude and longitude from android images when ExifInterface is failing.

### CODE REVIEW

**Comment by Sh1d0w** [comment]
Thank you very much for the PR and the fix. There were several reports for this, but I did not had the time to investigate.

Great work!

**Comment by b-jan** [comment]
@Quanalogy 

Can you help us on that issue: https://github.com/Sh1d0w/multi_image_picker/issues/232#issuecomment-525969032
Seems like the function `getLagLong(uri)` you implemented is not working anymore.

Thank you :smile:

**Comment by Quanalogy** [comment]
@b-jan yes I will look into it when I come home from work today, it is 6 in the morning for me, but hopefully I have an answer for you tonight :-)

**Comment by Quanalogy** [comment]
@b-jan I'm having issues with setting up my environment with flatpak, I won't fix it tonight but will look into it in the weekend. But if someone have a working environment, go debug the latlng function and see what the columnNames variable contains - post it here for example, it would help me fix it.

**Comment by b-jan** [comment]
@Quanalogy What do you use flatpak for?

**Comment by b-jan** [comment]
@Quanalogy Dis you see my comment about `latitude` : 
https://github.com/Sh1d0w/multi_image_picker/issues/232#issuecomment-525969032

**Comment by Quanalogy** [comment]
@b-jan it's the recommended way of installing applications in fedora silverblue, which I have recently changed to.

To your other comment yes I have seen it and I think you print the information out wrong. When I made that code I could by debugging to the cursor, see what it contained, which made it possible to fix with that way of indexing. That's why you need to see what the whole cursor contains.

**Comment by b-jan** [comment]
Cool, I'll try to debug on android studio tonight.

**Comment by b-jan** [comment]
I did not have time to investigate on this. Any update @Quanalogy ?

**Comment by Quanalogy** [comment]
@b-jan yes I have. The cursor no longer contains the contents of the metadata on newer version of android it would seem. I've for some time ago made a issue with Google as this is something with the standard library. At the time they said that it was an issue with the simulator and that it shouldn't be present within newer versions, but that seems not to be true.
The result of 0.0 is just how it is, no error in the code, but the cursor does not contain the data as it did before.

**Comment by Quanalogy** [comment]
@b-jan  @Sh1d0w I can however say that I've might found an alternative, using Exif (https://pub.dev/packages/exif) will solve the issue as I've got the following output by merging your example with his:

`for (var r in resultList) {
        var t = await r.filePath;

        var bytes = await new File(t).readAsBytes();
        var tags = await readExifFromBytes(bytes);
        var sb = StringBuffer();

        tags.forEach((k, v) {
          sb.write("$k: $v \n");
        });

        print(sb);
}`

Results in:

`
I/flutter ( 8857): Image Model: Android SDK built for x86 
I/flutter ( 8857): Image ImageWidth: 1080 
I/flutter ( 8857): Image ImageLength: 1920 
I/flutter ( 8857): Image DateTime: 2019:09:07 12:35:54 
I/flutter ( 8857): Image Orientation: Horizontal (normal) 
I/flutter ( 8857): Image ExifOffset: 163 
I/flutter ( 8857): GPS GPSLatitudeRef: N 
I/flutter ( 8857): GPS GPSLatitude: [37, 25, 608/25] 
I/flutter ( 8857): GPS GPSLongitudeRef: W 
I/flutter ( 8857): GPS GPSLongitude: [122, 5, 223/100] 
I/flutter ( 8857): GPS GPSTimeStamp: [10, 25, 57] 
I/flutter ( 8857): GPS GPSDate: 2019:09:07 
I/flutter ( 8857): Image GPSInfo: 441 
I/flutter ( 8857): Image Make: Google 
I/flutter ( 8857): EXIF FNumber: 14/5 
I/flutter ( 8857): EXIF ExposureTime: 6130639/500000000 
I/flutter ( 8857): EXIF SubSecTimeDigitized: 630 
I/flutter ( 8857): EXIF SubSecTimeOriginal: 630 
I/flutter ( 8857): EXIF SubSecTime: 630 
I/flutter ( 8857): EXIF FocalLength: 5 
I/flutter ( 8857): EXIF Flash: Flash did not fire 
I/flutter ( 8857): EXIF ISOSpeedRatings: 100 
I/flutter ( 8857): EXIF DateTimeDigitized: 2019:09:07 12:35:54 
I/flutter ( 8857): EXIF DateTimeOriginal: 2019:09:07 12:35:54 
I/flutter ( 8857): EXIF ExifImageLength: 1920 
I/flutter ( 8857): EXIF WhiteBalance: Auto 
I/flutter ( 8857): EXIF ExifImageWidth: 1080 
I/flutter ( 8857): EXIF ApertureValue: 297/100 
I/flutter ( 8857): EXIF ShutterSpeedValue: 6349/1000 
I/flutter ( 8857): EXIF ExifVersion: 0220 
I/flutter ( 8857): /storage/emulated/0/DCIM/Camera/IMG_20190907_123554.jpg
`

I think it would be better to use this instead of my workaround - which as the pull request also states is a tmp fix on the issue.

**Comment by b-jan** [comment]
Very nice !!! Can you open a Pull Request so that we start to move forward on the issue?

**Comment by Martibis** [comment]
> @Quanalogy Very nice !!! Can you open a Pull Request so that we start to move forward on the issue?

I tried with the EXIF package, but I was wondering how you are converting the values from the exif package for latitude to a double. I feel like I am missing something obvious, but parsing the values in the list to num and adding them up doesn't work for me.

**Pull request merged**
